workflows:
  build-apk:
    cache:
      cache_paths:
        - C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\Build.bat
    name: Build android apk
    triggering:
      events:
        - push
      cancel_previous_builds: false
    scripts:
      - C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\Build.bat  CIUe Android Development -Project=CIUe\CIUe.uproject -WaitMutex
      - cp CIUe/Binaries/Android/*.apk build/Android
    artifacts:
      - build/Android/*.apk
    publishing:
      email:
        recipients:
          - george.bebiya@mail.ru
        notify:
          success: true
          failure: false